//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVykEntities : DbContext
    {
        public CVykEntities()
            : base("name=CVykEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAnasayfa> TBLAnasayfa { get; set; }
        public virtual DbSet<TBLIletisimBilgi> TBLIletisimBilgi { get; set; }
        public virtual DbSet<TBLIletisimForm> TBLIletisimForm { get; set; }
        public virtual DbSet<TBLMenu> TBLMenu { get; set; }
        public virtual DbSet<TBLResimler> TBLResimler { get; set; }
        public virtual DbSet<TBLYetenekler> TBLYetenekler { get; set; }
    }
}
