//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAnasayfa
    {
        public int ID { get; set; }
        public string AnasayfaAcıklama { get; set; }
        public string AdSoyad { get; set; }
        public string İsTanımı { get; set; }
        public string AnasayfaAcıklama2 { get; set; }
        public string AnasayfaAcıklama3 { get; set; }
    }
}
