//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYetenekler
    {
        public int ID { get; set; }
        public string Yetenekler { get; set; }
        public Nullable<int> YetenekOranı { get; set; }
    }
}
