//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMusteri()
        {
            this.TBLSatis = new HashSet<TBLSatis>();
        }
    
        public int MusteriId { get; set; }
        [Required(ErrorMessage ="Bu Alan Boþ Býrakýlamaz...!!!")]
        [StringLength(50,ErrorMessage ="EN FAZLA 50 KARAKTER GÝRÝNÝZ...")]
        public string MusteriAd { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Býrakýlamaz...!!!")]
        [StringLength(50, ErrorMessage = "EN FAZLA 50 KARAKTER GÝRÝNÝZ...")]
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSatis> TBLSatis { get; set; }
    }
}
