//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSatis
    {
        public int SatisId { get; set; }
        public Nullable<int> Urun { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual TBLMusteri TBLMusteri { get; set; }
        public virtual TBLUrun TBLUrun { get; set; }
    }
}
