//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUrun()
        {
            this.TBLSatis = new HashSet<TBLSatis>();
        }
    
        public int UrunId { get; set; }
        
        public string UrunAd { get; set; }
        
        public Nullable<int> UrunKategori { get; set; }
        
        public Nullable<decimal> UrunFiyat { get; set; }
        
        public Nullable<int> UrunStok { get; set; }
        
        public string UrunMarka { get; set; }
    
        public virtual TBLKategori TBLKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSatis> TBLSatis { get; set; }
    }
}
